import keyMirror from 'keymirror';

export default keyMirror({
  OSC_CLOSE: null,
  OSC_ERROR: null,
  OSC_OPEN: null,
  OSC_READY: null,

  EDITOR_PARAMETER_SELECT: null,
  EDITOR_TOGGLE_SIDEBAR: null,

  PLAYER_STATE_CHANGE: null,

  SCENES_ADD: null,
  SCENES_LOAD: null,
  SCENES_REMOVE: null,
  SCENES_RESET: null,
  SCENES_SELECT: null,
  SCENES_UPDATE_PARAMETER: null,

  SETTINGS_LOAD: null,
  SETTINGS_NETWORK_SAVE: null,
  SETTINGS_PARAMETERS_ADD: null,
  SETTINGS_PARAMETERS_REMOVE: null,
  SETTINGS_RESET: null,

  SETUP_LOAD: null,
  SETUP_UPDATE_BEGIN: null,
  SETUP_UPDATE_END: null,

  TRANSPORT_PLAY: null,
  TRANSPORT_RECORD: null,
  TRANSPORT_SELECT_CUE_POINT: null,
  TRANSPORT_STATUS_RECEIVED: null,
  TRANSPORT_STOP: null,

  VIEW_CHANGE: null,
  VIEW_COLLAPSE_BAR: null,
  VIEW_EXPAND_BAR: null,
});
